source 'https://github.com/CocoaPods/Specs.git'

target 'GDIImageOperation', :exclusive => true do
  pod "GDIImageOperation", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "GDIImageOperation", :path => "../"

  
end
